import { Inter } from "next/font/google";
import "../../style/style.scss";
import "../globals.css";
import Script from 'next/script'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props) {
  const { children, params } = props;

  return (
    <html lang={params?.locale || 'en'}>
      <Script src="js/script.js"></Script>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
