import { Inter } from "next/font/google";
import { NextIntlClientProvider } from 'next-intl';
import { getMessages } from 'next-intl/server';

import "../../style/style.scss";
import "../globals.css";
import Script from 'next/script'


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function LocaleLayout(props) {
  const { children, params } = props;
  const messages = await getMessages();


  return (
    <html lang={params?.locale || 'en'}>
      <Script src="js/script.js"></Script>
      <body className={inter.className}>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
